import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import path from 'path';

export default defineConfig({
  plugins: [react()],
  build: {
    outDir: path.resolve(__dirname, '../st_automation/public/frontend'),
    emptyOutDir: true,
    rollupOptions: {
      output: {
        // Content-hashed filenames (was a fixed `index.js`/`index.css`) —
        // the fixed names meant every rebuild reused the exact same URL, so
        // the browser (Safari especially) kept serving old cached bundles
        // after a deploy even on a normal reload. This has already caused
        // two rounds of "the fix isn't showing up" confusion that were
        // actually just stale cache, not missing code. `index.html` is
        // regenerated by Vite on every build with the correct hashed paths
        // automatically, so no other file needs to change for this.
        entryFileNames: 'index-[hash].js',
        chunkFileNames: 'chunks/[name]-[hash].js',
        assetFileNames: (assetInfo) => {
          if (assetInfo.name && assetInfo.name.endsWith('.css')) {
            return 'index-[hash].css';
          }
          return 'assets/[name]-[hash][extname]';
        },
      },
    },
  },
  server: {
    port: 5173,
    proxy: {
      '/api': {
        target: 'http://127.0.0.1:8000',
        changeOrigin: true,
      },
      '/assets': {
        target: 'http://127.0.0.1:8000',
        changeOrigin: true,
      },
      '/files': {
        target: 'http://127.0.0.1:8000',
        changeOrigin: true,
      }
    },
  },
});
